In [1]:
import math
import numpy as np

# Informacje wstępne

To jest pierwszy **Notebook** w temacie: <span style="color:red; font-size:16pt;">Biblioteka NUMPY<span>
<br>
<img src="supernova.jpg">

In [2]:
def is_palindrome(word):
    word = word.lower()
    return word == word[::-1]

# demonstration
print(is_palindrome("Madam")) # True
print(is_palindrome("Python")) # False

True
False


In [3]:
np.zeros(18)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0.])

In [4]:
print(np.ones(9))

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
u = np.arange(1,87,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85])

In [9]:
print(type(u))

<class 'numpy.ndarray'>


In [10]:
zlista = [4,6,8,24,6,35,78,54,63,24,52,2,6,8,57,38]
print(zlista)
print(type(zlista))

[4, 6, 8, 24, 6, 35, 78, 54, 63, 24, 52, 2, 6, 8, 57, 38]
<class 'list'>


In [11]:
nplista = np.array(zlista)
print(nplista)
print(type(nplista))

[ 4  6  8 24  6 35 78 54 63 24 52  2  6  8 57 38]
<class 'numpy.ndarray'>


In [14]:
liczba = (44,5543,656,76,5,9,24)
npl = np.array(liczba)
print(npl)
print(type(npl))

[  44 5543  656   76    5    9   24]
<class 'numpy.ndarray'>


In [13]:
zb = {53,5,86,2,68,3,2,7,8,95,2}
zbn = np.array(zb)
print(zbn)
print(type(zbn))

{2, 3, 68, 5, 7, 8, 53, 86, 95}
<class 'numpy.ndarray'>


In [15]:
l1 = [2,3,6,7]
l2 = [12,16,34,66]
l3 = [45,12,38,90]

l1 = l1+l2+l3
l1
#konkatenacja list

[2, 3, 6, 7, 12, 16, 34, 66, 45, 12, 38, 90]

In [18]:
n1 = np.array([4,8,9,11])
n2 = np.array([23,35,48,96])
n3 = np.array([48,67,82,46])

# n1 = n1+n2+n3
# n1

n = np.concatenate((n1,n2,n3))
n

array([ 4, 8, 9, 11, 23, 35, 48, 96, 48, 67, 82, 46])