In [3]:
import math
import numpy as np

# Informacje wstępne

To jest pierwszy **Notebook** w temacie: <span style="color:red; font-size:16pt;">Biblioteka NUMPY<span>
<br>
<img src="supernova.jpg">

In [4]:
def is_palindrome(word):
    word = word.lower()
    return word == word[::-1]

# demonstration
print(is_palindrome("Madam")) # True
print(is_palindrome("Python")) # False

True
False


In [5]:
np.zeros(18)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0.])

In [6]:
print(np.ones(9))

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
u = np.arange(1,87,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85])

In [8]:
print(type(u))

<class 'numpy.ndarray'>


In [9]:
zlista = [4,6,8,24,6,35,78,54,63,24,52,2,6,8,57,38]
print(zlista)
print(type(zlista))

[4, 6, 8, 24, 6, 35, 78, 54, 63, 24, 52, 2, 6, 8, 57, 38]
<class 'list'>


In [10]:
nplista = np.array(zlista)
print(nplista)
print(type(nplista))

[ 4  6  8 24  6 35 78 54 63 24 52  2  6  8 57 38]
<class 'numpy.ndarray'>


In [11]:
liczba = (44,5543,656,76,5,9,24)
npl = np.array(liczba)
print(npl)
print(type(npl))

[  44 5543  656   76    5    9   24]
<class 'numpy.ndarray'>


In [12]:
zb = {53,5,86,2,68,3,2,7,8,95,2}
zbn = np.array(zb)
print(zbn)
print(type(zbn))

{2, 3, 68, 5, 7, 8, 53, 86, 95}
<class 'numpy.ndarray'>


In [13]:
l1 = [2,3,6,7]
l2 = [12,16,34,66]
l3 = [45,12,38,90]

l1 = l1+l2+l3
l1
#konkatenacja list

[2, 3, 6, 7, 12, 16, 34, 66, 45, 12, 38, 90]

In [14]:
n1 = np.array([4,8,9,11])
n2 = np.array([23,35,48,96])
n3 = np.array([48,67,82,46])

# n1 = n1+n2+n3
# n1

n = np.concatenate((n1,n2,n3))
n

array([ 4, 8, 9, 11, 23, 35, 48, 96, 48, 67, 82, 46])

In [15]:
z1 = [[4,6],[11,57]]
z1

[[4, 6], [11, 57]]

In [16]:
a1 = np.array([[5,35,2],[5,2,7],[787,37,8]])
a1

array([[ 5, 35, 2],
 [ 5, 2, 7],
 [787, 37, 8]])

In [17]:
z1[0]

[4, 6]

In [18]:
z1[0][1]

6

In [20]:
a1[0][1]

35

In [21]:
a1[0,1]

35

In [23]:
# z1[0,1]

In [27]:
x = np.array([[3,4],[6,8]])
y = np.array([[7,11],[19,3]])
p = np.concatenate((x,y),axis=1)
p

array([[ 3, 4, 7, 11],
 [ 6, 8, 19, 3]])

In [28]:
prosta = np.arange(12)
prosta

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [35]:
fp = prosta.reshape(3,4)
fp

array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11]])

In [36]:
mc1 = np.array([[2,3],[4,4],[9,8]])
mc1

array([[2, 3],
 [4, 4],
 [9, 8]])

In [40]:
mc1.reshape(6)

array([2, 3, 4, 4, 9, 8])

In [42]:
ar = np.array([6,2,6,2,78,-3,54,-34,12,-99,11,1,-4])

In [43]:
ar.shape

(13,)

In [44]:
mc1.shape

(3, 2)

In [45]:
w = np.array([[1,2,3,4],[6,8,9,11],[16,28,90,99]])

In [46]:
w[w<5]

array([1, 2, 3, 4])

In [47]:
pc = (w>=9)
w[pc]

array([ 9, 11, 16, 28, 90, 99])

In [48]:
pv = (w%2==0)
w[pv]

array([ 2, 4, 6, 8, 16, 28, 90])

In [51]:
cv = w[(w>2) & (w<22)]
cv

array([ 3, 4, 6, 8, 9, 11, 16])

In [52]:
w[(w<8)|(w>80)]

array([ 1, 2, 3, 4, 6, 90, 99])