In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [3]:
#transponowanie tablicy
arr.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [4]:
arr = np.random.randn(6,3)
arr

array([[-0.13031158, -0.99758093, -0.06772661],
 [ 1.02333126, -1.4067687 , -0.33692302],
 [-1.12724192, 1.26444137, -0.2599991 ],
 [-1.9835754 , 1.16685651, 0.23172566],
 [-1.02860278, 0.4485591 , -0.01235883],
 [ 0.29892238, 1.22849605, -0.28400048]])

In [5]:
arr.T

array([[-0.13031158, 1.02333126, -1.12724192, -1.9835754 , -1.02860278,
 0.29892238],
 [-0.99758093, -1.4067687 , 1.26444137, 1.16685651, 0.4485591 ,
 1.22849605],
 [-0.06772661, -0.33692302, -0.2599991 , 0.23172566, -0.01235883,
 -0.28400048]])

In [6]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [7]:
# arr.T

In [9]:
arr.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])